<?php 
/*
 * This file is part of BrilliantSearch-v2.0.3.1.zip.
 *
 * (c) Antropy <info@antropy.co.uk>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 *
 * Do not edit this file. Check http://www.opencart.com/index.php?route=extension/extension&filter_username=judge for updates.
 */
?><?php
// Heading
$_['heading_title']    = 'Brilliant Search';

$_['text_module']      = 'Modules';
$_['text_success']     = 'Success: You have modified Brilliant Search module!';

$_['text_ajax_enable']      = 'Enable Search Suggestions';
$_['text_ajax_max_results_total'] = 'Maximum Suggestions Total';
$_['help_ajax_max_results_total'] = 'The total number of items (categories and products) suggested while the user types.';
$_['text_ajax_max_results_cats']  = 'Maximum Suggestions Categories';
$_['help_ajax_max_results_cats']  = 'The number of categories suggested while the user types. It should be lower than the Maximum Suggestions Total.';
$_['text_ajax_max_results_prods'] = 'Maximum Suggestions Products';
$_['help_ajax_max_results_prods']  = 'The number of products suggested while the user types. It should be lower than the Maximum Suggestions Total.';
$_['text_ajax_type_delay']        = 'Type delay';
$_['help_ajax_type_delay']        = 'In ms. The time the use must not press a key before the search is submitted. A good value is 500.';
$_['text_fuzzyness']              = 'Fuzzyness';
$_['help_fuzzyness'] = 'A value in % between 100 (100% identical) and 0(not identical). The higher the value the faster the search will be but more of the spelling mistakes will not be corrected. A good value is around 70.';
$_['text_include_categories'] = 'Include Categories';

$_['error_ajax_max_results_total'] = 'Please enter the total number of search results suggested while the user types.';
$_['error_ajax_max_results_cats'] = 'Please enter the total number of categories suggested while the user types.';
$_['error_ajax_max_results_prods'] = 'Please enter the total number of products suggested while the user types.';
$_['error_ajax_type_delay'] = 'Please enter a delay in ms as a natural number greater than 0.';
$_['error_search_fuzzyness'] = 'Please enter a fuzzyness grate (in percent) between 0 and 100, e.g. 70';
$_['text_edit']        = 'Edit Brilliant Search Module';

// Entry
$_['entry_status']     = 'Status';

// Error
$_['error_permission'] = 'Warning: You do not have permission to modify Brilliant Search module!';